version: '3.3'
services:
        reparam:
          build:
            context: ./
            args:
              USER_ID: ${USERID}
              GROUP_ID: ${GROUPID}
              USER_NAME: ${USERNAME}
          image: "reparam_raspberry5"
          container_name: ${CONTAINERNAME} 
          network_mode: "host"
          volumes:
            - "/home/${USERNAME}/workspace:/workspace"
          environment:
            - "DISPLAY"
          device_cgroup_rules:
            - "c 81:* rmw"
            - "c 189:* rmw"
          stdin_open: true
          tty: true